source 'https://rubygems.org'
gem "middleman"

gem "rouge"

# middleman-syntax from git just for good measure and more alignment with rouge
gem "middleman-syntax", git: 'https://github.com/middleman/middleman-syntax.git'

# redcarpet from git to get github-style anchors
gem "redcarpet"

gem "middleman-livereload"
gem 'middleman-s3_sync'
gem 'middleman-blog'

gem 'rspec'
gem 'xmlrpc'
