source 'https://rubygems.org'
gem "therubyracer"
gem "middleman", "~>3.1.5"

gem "rouge", "~> 1.2.0"

# middleman-syntax from git just for good measure and more alignment with rouge
gem "middleman-syntax", git: 'https://github.com/middleman/middleman-syntax.git'

# redcarpet from git to get github-style anchors
gem "redcarpet", git: 'https://github.com/vmg/redcarpet.git'

gem "middleman-livereload", "~> 3.1.0"
gem "middleman-deploy"

gem 'rspec'
